# Generated by Django 5.2.7 on 2025-10-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['student', 'timestamp'], name='api_attempt_student_992dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='attempt',
            index=models.Index(fields=['lesson', 'timestamp'], name='api_attempt_lesson__ccb0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['course', 'order_index'], name='api_lesson_course__b3610e_idx'),
        ),
    ]
