# Generated by Django 5.2.7 on 2025-10-23 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attempt_api_attempt_student_992dcb_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice Question'), ('coding', 'Coding Problem'), ('text', 'Text Input')], default='mcq', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('options', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField()),
                ('difficulty', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=10)),
                ('order_index', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lesson')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('order_index', models.IntegerField()),
                ('penalty_points', models.IntegerField(default=2)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='api.question')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('answer', models.JSONField()),
                ('is_correct', models.BooleanField()),
                ('hints_used', models.IntegerField(default=0)),
                ('duration_sec', models.IntegerField()),
                ('points_earned', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_attempts', to='api.student')),
            ],
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['lesson', 'order_index'], name='api_questio_lesson__35d870_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['student', 'timestamp'], name='api_questio_student_2213df_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['question', 'timestamp'], name='api_questio_questio_242283_idx'),
        ),
        migrations.AddIndex(
            model_name='questionattempt',
            index=models.Index(fields=['student', 'question'], name='api_questio_student_a26dd2_idx'),
        ),
    ]
